/*
 * Constant definitions for the Pageant resource file.
 */

#define IDI_MAINICON 200
#define IDI_TRAYICON 201

#define IDD_KEYLIST 211
#define IDD_LOAD_PASSPHRASE 210
#define IDD_ONDEMAND_PASSPHRASE 212
#define IDD_ABOUT 213
#define IDD_LICENCE 214

#define IDC_PASSPHRASE_STATIC1 100
#define IDC_PASSPHRASE_FINGERPRINT 101
#define IDC_PASSPHRASE_STATIC2 102
#define IDC_PASSPHRASE_STATIC3 103
#define IDC_PASSPHRASE_EDITBOX 104

#define IDC_KEYLIST_LISTBOX 100
#define IDC_KEYLIST_ADDKEY 101
#define IDC_KEYLIST_ADDKEY_ENC 110
#define IDC_KEYLIST_REENCRYPT 106
#define IDC_KEYLIST_REMOVE 102
#define IDC_KEYLIST_HELP 103
#define IDC_KEYLIST_FPTYPE_STATIC 104
#define IDC_KEYLIST_FPTYPE 105

#define IDC_ABOUT_LICENCE 101
#define IDC_ABOUT_WEBSITE 102
#define IDC_ABOUT_TEXTBOX 1000

#define IDC_LICENCE_TEXTBOX 1000
