.TH plink 1
.SH NAME
plink \- PuTTY link, command line network connection tool
.SH SYNOPSIS
\fBplink\fR [\fIoptions\fR] [\fIuser\fB@\fR]\fIhost\fR [\fIcommand\fR]
.SH DESCRIPTION
\fBplink\fR is a network connection tool supporting several protocols.
.SH OPTIONS
The command-line options supported by \fIplink\fP are:
.IP "\fB-v\fR"
Show verbose messages.
.IP "\fB-load\fR \fIsession\fR"
Load settings from saved session.
.IP "\fB-ssh\fR"
Force use of SSH protocol (default).
.IP "\fB-telnet\fR"
Force use of Telnet protocol.
.IP "\fB-rlogin\fR"
Force use of rlogin protocol.
.IP "\fB-raw\fR"
Force raw mode.
.IP "\fB-P\fR \fIport\fR"
Connect to port \fIport\fR.
.IP "\fB-l\fR \fIuser\fR"
Set remote username to \fIuser\fR.
.IP "\fB-m\fR \fIpath\fR"
Read remote command(s) from local file \fIpath\fR.
.IP "\fB-batch\fR"
Disable interactive prompts.
.IP "\fB-pw\fR \fIpassword\fR"
Set remote password to \fIpassword\fR.
.IP "\fB-L\fR [\fIlisten-IP\fB:\fR]\fIlisten\fB:\fIhost\fB:\fIport\fR"
Forward the local port to a remote address.
.IP "\fB-R\fR [\fIlisten-IP\fB:\fR]\fIlisten\fB:\fIhost\fB:\fIport\fR"
Forward the a remote port to a local address.
.IP "\fB-D\fR [\fIlisten-IP\fB:\fR]\fIlisten-port\fR"
Dynamic port forwarding: start a SOCKS server on \fIlisten-port\fR.
.IP "\fB-X\fR"
Enable X11 forwarding.
.IP "\fB-x\fR"
Disable X11 forwarding (default).
.IP "\fB-A\fR"
Enable agent forwarding.
.IP "\fB-a\fR"
Disable agent forwarding (default).
.IP "\fB-t\fR"
Enable pty allocation (default if a command is NOT specified).
.IP "\fB-T\fR"
Disable pty allocation (default if a command is specified).
.IP "\fB-1\fR"
Force use of SSH protocol version 1.
.IP "\fB-2\fR"
Force use of SSH protocol version 2.
.IP "\fB-C\fR"
Enable SSH compression.
.IP "\fB-i\fR \fIpath\fR"
Private key file for authentication.
.IP "\fB-s\fR"
Remote command is SSH subsystem (SSH-2 only).
.SH MORE INFORMATION
For more information on plink, it's probably best to go and look at
the manual on the PuTTY web page:

\fBhttp://www.chiark.greenend.org.uk/~sgtatham/putty/\fP
.SH BUGS
This man page isn't terribly complete. See the above web link for
better documentation.
