.TH pscp 1
.SH NAME
pscp \- command-line SCP (secure copy) / SFTP client
.SH SYNOPSIS
\fBpscp\fR [\fIoptions\fR] [\fIuser\fB@\fR]\fIhost\fB:\fIsource\fR \fItarget\fR
.br
\fBpscp\fR [\fIoptions\fR] \fIsource\fR [\fIsource\fR...] [\fIuser\fB@\fR]\fIhost\fB:\fItarget\fR
.br
\fBpscp\fR [\fIoptions\fR] \fB-ls\fR [\fIuser\fB@\fR]\fIhost\fB:\fIfilespec\fR
.SH DESCRIPTION
\fBpscp\fR is a command-line client for the SSH-based SCP (secure
copy) and SFTP (secure file transfer protocol) protocols.
.SH OPTIONS
The command-line options supported by \fIpscp\fP are:
.IP "\fB-ls\fR"
Remote directory listing.
.IP "\fB-p\fR"
Preserve file attributes.
.IP "\fB-q\fR"
Quiet, don't show statistics.
.IP "\fB-r\fR"
Copy directories recursively.
.IP "\fB-unsafe\fR"
Allow server-side wildcards (DANGEROUS).
.IP "\fB-v\fR"
Show verbose messages.
.IP "\fB-load\fR \fIsession\fR"
Load settings from saved session.
.IP "\fB-P\fR \fIport\fR"
Connect to port \fIport\fR.
.IP "\fB-l\fR \fIuser\fR"
Set remote username to \fIuser\fR.
.IP "\fB-batch\fR"
Disable interactive prompts.
.IP "\fB-pw\fR \fIpassword\fR"
Set remote password to \fIpassword\fR.
.IP "\fB-1\fR"
Force use of SSH protocol version 1.
.IP "\fB-2\fR"
Force use of SSH protocol version 2.
.IP "\fB-C\fR"
Enable SSH compression.
.IP "\fB-i\fR \fIpath\fR"
Private key file for authentication.
.SH MORE INFORMATION
For more information on \fBpscp\fR it's probably best to go and look at
the manual on the PuTTY web page:

\fBhttp://www.chiark.greenend.org.uk/~sgtatham/putty/\fP
.SH BUGS
This man page isn't terribly complete. See the above web link for
better documentation.
