.TH psftp 1
.SH NAME
psftp \- interactive SFTP (secure file transfer protocol) client
.SH SYNOPSIS
\fBpsftp\fR [\fIoptions\fR] [\fIuser\fB@\fR]\fIhost\fR
.SH DESCRIPTION
\fBpsftp\fR is an interactive text-based client for the SSH-based SFTP
(secure file transfer) protocol.
.SH OPTIONS
The command-line options supported by \fIpsftp\fP are:
.IP "\fB-b\fR \fIbatchfile\fR"
Use specified batchfile.
.IP "\fB-bc\fR"
Output batchfile commands.
.IP "\fB-be\fR"
Don't stop batchfile processing on errors.
.IP "\fB-v\fR"
Show verbose messages.
.IP "\fB-load\fR \fIsession\fR"
Load settings from saved session.
.IP "\fB-P\fR \fIport\fR"
Connect to port \fIport\fR.
.IP "\fB-l\fR \fIuser\fR"
Set remote username to \fIuser\fR.
.IP "\fB-batch\fR"
Disable interactive prompts.
.IP "\fB-pw\fR \fIpassword\fR"
Set remote password to \fIpassword\fR.
.IP "\fB-1\fR"
Force use of SSH protocol version 1.
.IP "\fB-2\fR"
Force use of SSH protocol version 2.
.IP "\fB-C\fR"
Enable SSH compression.
.IP "\fB-i\fR \fIpath\fR"
Private key file for authentication.
.SH COMMANDS
For a list of commands available inside \fBpsftp\fR, type \fBhelp\fR
at the \fBpsftp>\fR prompt.
.SH MORE INFORMATION
For more information on \fBpsftp\fR it's probably best to go and look at
the manual on the PuTTY web page:

\fBhttp://www.chiark.greenend.org.uk/~sgtatham/putty/\fP
.SH BUGS
This man page isn't terribly complete. See the above web link for
better documentation.
