.TH pterm 1
.UC
.SH NAME
pterm \- yet another X terminal emulator
.SH SYNOPSIS
\fBpterm\fP [ \fIoptions\fP ]
.SH DESCRIPTION
\fIpterm\fP is a terminal emulator for X. It is based on a port of
the terminal emulation engine in the Windows SSH client PuTTY.
.SH OPTIONS
The command-line options supported by \fIpterm\fP are:
.IP "\fB\-e\fP \fIcommand\fP [ \fIarguments\fP ]"
Specify a command to be executed in the new terminal. Everything on
the command line after this option will be passed straight to the
\fIexecvp\fP system call; so if you need the command to redirect its
input or output, you will have to use \fIsh\fP:

pterm \-e sh \-c 'mycommand < inputfile'
.IP "\fB\-\-display\fP \fIdisplay\-name\fP"
Specify the X display on which to open \fIpterm\fP. (Note this
option has a double minus sign, even though none of the others do.
This is because this option is supplied automatically by GTK.
Sorry.)
.IP "\fB\-name\fP \fIfont-name\fP"
Specify the name under which \fIpterm\fP looks up X resources.
Normally it will look them up as (for example) \fBpterm.Font\fP. If
you specify "\-name xyz", it will look them up as \fBxyz.Font\fP
instead. This allows you to set up several different sets of
defaults and choose between them.
.IP "\fB\-fn\fP \fIfont-name\fP"
Specify the font to use for normal text displayed in the terminal.
.IP "\fB\-fb\fP \fIfont-name\fP"
Specify the font to use for bold text displayed in the terminal. If
the \fIBoldAsColour\fP resource is set to 1 (the default), bold text
will be displayed in different colours instead of a different font,
so this option will be ignored. If \fIBoldAsColour\fP is set to 0
and you do not specify a bold font, \fIpterm\fP will overprint the
normal font to make it look bolder.
.IP "\fB\-fw\fP \fIfont-name\fP"
Specify the font to use for double-width characters (typically
Chinese, Japanese and Korean text) displayed in the terminal.
.IP "\fB\-fwb\fP \fIfont-name\fP"
Specify the font to use for bold double-width characters (typically
Chinese, Japanese and Korean text) Like \fI-fb\fP, this will be
ignored unless the \fIBoldAsColour\fP resource is set to 0.
.IP "\fB\-geometry\fP \fIgeometry\fP"
Specify the size of the terminal, in rows and columns of text. See
\fIX(7)\fP for more information on the syntax of geometry
specifications.
.IP "\fB\-sl\fP \fIlines\fP"
Specify the number of lines of scrollback to save off the top of the
terminal.
.IP "\fB\-fg\fP \fIcolour\fP"
Specify the foreground colour to use for normal text.
.IP "\fB\-bg\fP \fIcolour\fP"
Specify the background colour to use for normal text.
.IP "\fB\-bfg\fP \fIcolour\fP"
Specify the foreground colour to use for bold text, if the
\fIBoldAsColour\fP resource is set to 1 (the default).
.IP "\fB\-bbg\fP \fIcolour\fP"
Specify the foreground colour to use for bold reverse-video text, if
the \fIBoldAsColour\fP resource is set to 1 (the default). (This
colour is best thought of as the bold version of the background
colour; so it only appears when text is displayed \fIin\fP the
background colour.)
.IP "\fB\-cfg\fP \fIcolour\fP"
Specify the foreground colour to use for text covered by the cursor.
.IP "\fB\-cbg\fP \fIcolour\fP"
Specify the background colour to use for text covered by the cursor.
In other words, this is the main colour of the cursor.
.IP "\fB\-title\fP \fItitle\fP"
Specify the initial title of the terminal window. (This can be
changed under control of the server.)
.IP "\fB\-ut\-\fP or \fB+ut\fP"
Tells \fIpterm\fP not to record your login in the \fIutmp\fP,
\fIwtmp\fP and \fIlastlog\fP system log files; so you will not show
up on \fIfinger\fP or \fIwho\fP listings, for example.
.IP "\fB\-ut\fP"
Tells \fIpterm\fP to record your login in \fIutmp\fP, \fIwtmp\fP and
\fIlastlog\fP: this is the opposite of \fI\-ut\-\fP. This is the
default option: you will probably only need to specify it explicitly
if you have changed the default using the \fIStampUtmp\fP resource.
.IP "\fB\-ls\-\fP or \fB+ls\fP"
Tells \fIpterm\fP not to execute your shell as a login shell.
.IP "\fB\-ls\fP"
Tells \fIpterm\fP to execute your shell as a login shell: this is
the opposite of \fI\-ls\-\fP. This is the default option: you will
probably only need to specify it explicitly if you have changed the
default using the \fILoginShell\fP resource.
.IP "\fB\-sb\-\fP or \fB+sb\fP"
Tells \fIpterm\fP not to display a scroll bar.
.IP "\fB\-sb\fP"
Tells \fIpterm\fP to display a scroll bar: this is the opposite of
\fI\-sb\-\fP. This is the default option: you will probably only need
to specify it explicitly if you have changed the default using the
\fIScrollBar\fP resource.
.IP "\fB\-log\fP \fIfilename\fP"
This option makes \fIpterm\fP log all the terminal output to a file
as well as displaying it in the terminal.
.IP "\fB\-cs\fP \fIcharset\fP"
This option specifies the character set in which \fIpterm\fP should
assume the session is operating. This character set will be used to
interpret all the data received from the session, and all input you
type or paste into \fIpterm\fP will be converted into this character
set before being sent to the session.

Any character set name which is valid in a MIME header (and
supported by \fIpterm\fP) should be valid here (examples are
"ISO-8859-1", "windows-1252" or "UTF-8"). Also, any character
encoding which is valid in an X logical font description should be
valid ("ibm-cp437", for example).

\fIpterm\fP's default behaviour is to use the same character
encoding as its primary font. If you supply a Unicode (iso10646-1)
font, it will default to the UTF-8 character set.

Character set names are case-insensitive.
.IP "\fB\-nethack\fP"
Tells \fIpterm\fP to enable NetHack keypad mode, in which the
numeric keypad generates the NetHack "hjklyubn" direction keys. This
enables you to play NetHack with the numeric keypad without having
to use the NetHack "number_pad" option (which requires you to press
"n" before any repeat count). So you can move with the numeric
keypad, and enter repeat counts with the normal number keys.
.IP "\fB\-xrm\fP \fIresource-string\fP"
This option specifies an X resource string. Useful for setting
resources which do not have their own command-line options. For
example:

pterm \-xrm 'ScrollbarOnLeft: 1'
.IP "\fB\-help\fP, \fB\-\-help\fP"
Display a message summarizing the available options.
.SH X RESOURCES
\fIpterm\fP can be more completely configured by means of X
resources. All of these resources are of the form \fIpterm.FOO\fP
for some FOO; you can make \fIpterm\fP look them up under another
name, such as \fIxyz.FOO\fP, by specifying the command-line option
"\-name xyz".
.IP "\fBpterm.CloseOnExit\fP"
This option should be set to 0, 1 or 2; the default is 2. It
controls what \fIpterm\fP does when the process running inside it
terminates. When set to 2 (the default), \fIpterm\fP will close its
window as soon as the process inside it terminates. When set to 0,
\fIpterm\fP will print the process's exit status, and the window
will remain present until a key is pressed (allowing you to inspect
the scrollback, and copy and paste text out of it).

When this setting is set to 1, \fIpterm\fP will close
immediately if the process exits cleanly (with an exit status of
zero), but the window will stay around if the process exits with a
non-zero code or on a signal. This enables you to see what went
wrong if the process suffers an error, but not to have to bother
closing the window in normal circumstances.
.IP "\fBpterm.WarnOnClose\fP"
This option should be set to either 0 or 1; the default is 1.
When set to 1, \fIpterm\fP will ask for confirmation before closing
its window when you press the close button.
.IP "\fBpterm.TerminalType\fP"
This controls the value set in the TERM environment variable inside
the new terminal. The default is "xterm".
.IP "\fBpterm.BackspaceIsDelete\fP"
This option should be set to either 0 or 1; the default is 1. When
set to 0, the ordinary Backspace key generates the Backspace
character (^H); when set to 1, it generates the Delete character
(^?). Whichever one you set, the terminal device inside \fIpterm\fP
will be set up to expect it.
.IP "\fBpterm.RXVTHomeEnd\fP"
This option should be set to either 0 or 1; the default is 0. When
it is set to 1, the Home and End keys generate the control sequences
they would generate in the \fIrxvt\fP terminal emulator, instead of
the more usual ones generated by other emulators.
.IP "\fBpterm.LinuxFunctionKeys\fP"
This option can be set to any number between 0 and 5 inclusive; the
default is 0. The modes vary the control sequences sent by the
function keys; for more complete documentation, it is probably
simplest to try each option in "pterm \-e cat", and press the keys to
see what they generate.
.IP "\fBpterm.NoApplicationKeys\fP"
This option should be set to either 0 or 1; the default is 0. When
set to 1, it stops the server from ever switching the numeric keypad
into application mode (where the keys send function-key-like
sequences instead of numbers or arrow keys). You probably only need
this if some application is making a nuisance of itself.
.IP "\fBpterm.NoApplicationCursors\fP"
This option should be set to either 0 or 1; the default is 0. When
set to 1, it stops the server from ever switching the cursor keys
into application mode (where the keys send slightly different
sequences). You probably only need this if some application is
making a nuisance of itself.
.IP "\fBpterm.NoMouseReporting\fP"
This option should be set to either 0 or 1; the default is 0. When
set to 1, it stops the server from ever enabling mouse reporting
mode (where mouse clicks are sent to the application instead of
controlling cut and paste).
.IP "\fBpterm.NoRemoteResize\fP"
This option should be set to either 0 or 1; the default is 0. When
set to 1, it stops the server from being able to remotely control
the size of the \fIpterm\fP window.
.IP "\fBpterm.NoAltScreen\fP"
This option should be set to either 0 or 1; the default is 0. When
set to 1, it stops the server from using the "alternate screen"
terminal feature, which lets full-screen applications leave the
screen exactly the way they found it.
.IP "\fBpterm.NoRemoteWinTitle\fP"
This option should be set to either 0 or 1; the default is 0. When
set to 1, it stops the server from remotely controlling the title of
the \fIpterm\fP window.
.IP "\fBpterm.NoRemoteQTitle\fP"
This option should be set to either 0 or 1; the default is 1. When
set to 1, it stops the server from remotely requesting the title of
the \fIpterm\fP window.

This feature is a \fBPOTENTIAL SECURITY HAZARD\fP. If a malicious
application can write data to your terminal (for example, if you
merely \fIcat\fP a file owned by someone else on the server
machine), it can change your window title (unless you have disabled
this using the \fBNoRemoteWinTitle\fP resource) and then use this
service to have the new window title sent back to the server as if
typed at the keyboard. This allows an attacker to fake keypresses
and potentially cause your server-side applications to do things you
didn't want. Therefore this feature is disabled by default, and we
recommend you do not turn it on unless you \fBreally\fP know what
you are doing.
.IP "\fBpterm.NoDBackspace\fP"
This option should be set to either 0 or 1; the default is 0. When
set to 1, it disables the normal action of the Delete (^?) character
when sent from the server to the terminal, which is to move the
cursor left by one space and erase the character now under it.
.IP "\fBpterm.ApplicationCursorKeys\fP"
This option should be set to either 0 or 1; the default is 0. When
set to 1, the default initial state of the cursor keys are
application mode (where the keys send function-key-like sequences
instead of numbers or arrow keys). When set to 0, the default state
is the normal one.
.IP "\fBpterm.ApplicationKeypad\fP"
This option should be set to either 0 or 1; the default is 0. When
set to 1, the default initial state of the numeric keypad is
application mode (where the keys send function-key-like sequences
instead of numbers or arrow keys). When set to 0, the default state
is the normal one.
.IP "\fBpterm.NetHackKeypad\fP"
This option should be set to either 0 or 1; the default is 0. When
set to 1, the numeric keypad operates in NetHack mode. This is
equivalent to the \fI\-nethack\fP command-line option.
.IP "\fBpterm.Answerback\fP"
This option controls the string which the terminal sends in response
to receiving the ^E character ("tell me about yourself"). By default
this string is "PuTTY".
.IP "\fBpterm.HideMousePtr\fP"
This option should be set to either 0 or 1; the default is 0. When
it is set to 1, the mouse pointer will disappear if it is over the
\fIpterm\fP window and you press a key. It will reappear as soon as
you move it.
.IP "\fBpterm.WindowBorder\fP"
This option controls the number of pixels of space between the text
in the \fIpterm\fP window and the window frame. The default is 1.
You can increase this value, but decreasing it to 0 is not
recommended because it can cause the window manager's size hints to
work incorrectly.
.IP "\fBpterm.CurType\fP"
This option should be set to either 0, 1 or 2; the default is 0.
When set to 0, the text cursor displayed in the window is a
rectangular block. When set to 1, the cursor is an underline; when
set to 2, it is a vertical line.
.IP "\fBpterm.BlinkCur\fP"
This option should be set to either 0 or 1; the default is 0. When
it is set to 1, the text cursor will blink when the window is active.
.IP "\fBpterm.Beep\fP"
This option should be set to either 0 or 2 (yes, 2); the default is
0. When it is set to 2, \fIpterm\fP will respond to a bell character
(^G) by flashing the window instead of beeping.
.IP "\fBpterm.BellOverload\fP"
This option should be set to either 0 or 1; the default is 0. When
it is set to 1, \fIpterm\fP will watch out for large numbers of
bells arriving in a short time and will temporarily disable the bell
until they stop. The idea is that if you \fIcat\fP a binary file,
the frantic beeping will mostly be silenced by this feature and will
not drive you crazy.

The bell overload mode is activated by receiving N bells in time T;
after a further time S without any bells, overload mode will turn
itself off again.

Bell overload mode is always deactivated by any keypress in the
terminal. This means it can respond to large unexpected streams of
data, but does not interfere with ordinary command-line activities
that generate beeps (such as filename completion).
.IP "\fBpterm.BellOverloadN\fP"
This option counts the number of bell characters which will activate
bell overload if they are received within a length of time T. The
default is 5.
.IP "\fBpterm.BellOverloadT\fP"
This option specifies the time period in which receiving N or more
bells will activate bell overload mode. It is measured in
microseconds, so (for example) set it to 1000000 for one second. The
default is 2000000 (two seconds).
.IP "\fBpterm.BellOverloadS\fP"
This option specifies the time period of silence required to turn
off bell overload mode. It is measured in microseconds, so (for
example) set it to 1000000 for one second. The default is 5000000
(five seconds of silence).
.IP "\fBpterm.ScrollbackLines\fP"
This option specifies how many lines of scrollback to save above the
visible terminal screen. The default is 200. This resource is
equivalent to the \fI\-sl\fP command-line option.
.IP "\fBpterm.DECOriginMode\fP"
This option should be set to either 0 or 1; the default is 0. It
specifies the default state of DEC Origin Mode. (If you don't know
what that means, you probably don't need to mess with it.)
.IP "\fBpterm.AutoWrapMode\fP"
This option should be set to either 0 or 1; the default is 1. It
specifies the default state of auto wrap mode. When set to 1, very
long lines will wrap over to the next line on the terminal; when set
to 0, long lines will be squashed against the right-hand edge of the
screen.
.IP "\fBpterm.LFImpliesCR\fP"
This option should be set to either 0 or 1; the default is 0. When
set to 1, the terminal will return the cursor to the left side of
the screen when it receives a line feed character.
.IP "\fBpterm.WinTitle\fP"
This resource is the same as the \fI\-T\fP command-line option: it
controls the initial title of the window. The default is "pterm".
.IP "\fBpterm.TermWidth\fP"
This resource is the same as the width part of the \fI\-geometry\fP
command-line option: it controls the number of columns of text in
the window. The default is 80.
.IP "\fBpterm.TermHeight\fP"
This resource is the same as the width part of the \fI\-geometry\fP
command-line option: it controls the number of columns of text in
the window. The defaults is 24.
.IP "\fBpterm.Font\fP"
This resource is the same as the \fI\-fn\fP command-line option: it
controls the font used to display normal text. The default is
"fixed".
.IP "\fBpterm.BoldFont\fP"
This resource is the same as the \fI\-fb\fP command-line option: it
controls the font used to display bold text when \fIBoldAsColour\fP
is turned off. The default is unset (the font will be bolded by
printing it twice at a one-pixel offset).
.IP "\fBpterm.WideFont\fP"
This resource is the same as the \fI\-fw\fP command-line option: it
controls the font used to display double-width characters. The
default is unset (double-width characters cannot be displayed).
.IP "\fBpterm.WideBoldFont\fP"
This resource is the same as the \fI\-fwb\fP command-line option: it
controls the font used to display double-width characters in bold,
when \fIBoldAsColour\fP is turned off. The default is unset
(double-width characters are displayed in bold by printing them
twice at a one-pixel offset).
.IP "\fBpterm.ShadowBoldOffset\fP"
This resource can be set to an integer; the default is \-1. It
specifies the offset at which text is overprinted when using "shadow
bold" mode. The default (1) means that the text will be printed in
the normal place, and also one character to the right; this seems to
work well for most X bitmap fonts, which have a blank line of pixels
down the right-hand side. For some fonts, you may need to set this to
\-1, so that the text is overprinted one pixel to the left; for
really large fonts, you may want to set it higher than 1 (in one
direction or the other).
.IP "\fBpterm.BoldAsColour\fP"
This option should be set to either 0 or 1; the default is 1. It
specifies the default state of auto wrap mode. When set to 1, bold
text is shown by displaying it in a brighter colour; when set to 0,
bold text is shown by displaying it in a heavier font.
.IP "\fBpterm.Colour0\fP, \fBpterm.Colour1\fP, ..., \fBpterm.Colour21\fP"
These options control the various colours used to display text in
the \fIpterm\fP window. Each one should be specified as a triple of
decimal numbers giving red, green and blue values: so that black is
"0,0,0", white is "255,255,255", red is "255,0,0" and so on.

Colours 0 and 1 specify the foreground colour and its bold
equivalent (the \fI\-fg\fP and \fI\-bfg\fP command-line options).
Colours 2 and 3 specify the background colour and its bold
equivalent (the \fI\-bg\fP and \fI\-bbg\fP command-line options).
Colours 4 and 5 specify the text and block colours used for the
cursor (the \fI\-cfg\fP and \fI\-cbg\fP command-line options). Each
even number from 6 to 20 inclusive specifies the colour to be used
for one of the ANSI primary colour specifications (black, red,
green, yellow, blue, magenta, cyan, white, in that order); the odd
numbers from 7 to 21 inclusive specify the bold version of each
colour, in the same order. The defaults are:

.nf
pterm.Colour0: 187,187,187
pterm.Colour1: 255,255,255
pterm.Colour2: 0,0,0
pterm.Colour3: 85,85,85
pterm.Colour4: 0,0,0
pterm.Colour5: 0,255,0
pterm.Colour6: 0,0,0
pterm.Colour7: 85,85,85
pterm.Colour8: 187,0,0
pterm.Colour9: 255,85,85
pterm.Colour10: 0,187,0
pterm.Colour11: 85,255,85
pterm.Colour12: 187,187,0
pterm.Colour13: 255,255,85
pterm.Colour14: 0,0,187
pterm.Colour15: 85,85,255
pterm.Colour16: 187,0,187
pterm.Colour17: 255,85,255
pterm.Colour18: 0,187,187
pterm.Colour19: 85,255,255
pterm.Colour20: 187,187,187
pterm.Colour21: 255,255,255
.fi
.IP "\fBpterm.RectSelect\fP"
This option should be set to either 0 or 1; the default is 0. When
set to 0, dragging the mouse over several lines selects to the end
of each line and from the beginning of the next; when set to 1,
dragging the mouse over several lines selects a rectangular region.
In each case, holding down Alt while dragging gives the other
behaviour.
.IP "\fBpterm.MouseOverride\fP"
This option should be set to either 0 or 1; the default is 1. When
set to 1, if the application requests mouse tracking (so that mouse
clicks are sent to it instead of doing selection), holding down
Shift will revert the mouse to normal selection. When set to 0,
mouse tracking completely disables selection.
.IP "\fBpterm.Printer\fP"
This option is unset by default. If you set it, then
server-controlled printing is enabled: the server can send control
sequences to request data to be sent to a printer. That data will be
piped into the command you specify here; so you might want to set it
to "lpr", for example, or "lpr \-Pmyprinter".
.IP "\fBpterm.ScrollBar\fP"
This option should be set to either 0 or 1; the default is 1. When
set to 0, the scrollbar is hidden (although Shift-PageUp and
Shift-PageDown still work). This is the same as the \fI\-sb\fP
command-line option.
.IP "\fBpterm.ScrollbarOnLeft\fP"
This option should be set to either 0 or 1; the default is 0. When
set to 1, the scrollbar will be displayed on the left of the
terminal instead of on the right.
.IP "\fBpterm.ScrollOnKey\fP"
This option should be set to either 0 or 1; the default is 0. When
set to 1, any keypress causes the position of the scrollback to be
reset to the very bottom.
.IP "\fBpterm.ScrollOnDisp\fP"
This option should be set to either 0 or 1; the default is 1. When
set to 1, any activity in the display causes the position of the
scrollback to be reset to the very bottom.
.IP "\fBpterm.LineCodePage\fP"
This option specifies the character set to be used for the session.
This is the same as the \fI\-cs\fP command-line option.
.IP "\fBpterm.NoRemoteCharset\fP"
This option disables the terminal's ability to change its character
set when it receives escape sequences telling it to. You might need
to do this to interoperate with programs which incorrectly change
the character set to something they think is sensible.
.IP "\fBpterm.BCE\fP"
This option should be set to either 0 or 1; the default is 1. When
set to 1, the various control sequences that erase parts of the
terminal display will erase in whatever the current background
colour is; when set to 0, they will erase in black always.
.IP "\fBpterm.BlinkText\fP"
This option should be set to either 0 or 1; the default is 0. When
set to 1, text specified as blinking by the server will actually
blink on and off; when set to 0, \fIpterm\fP will use the less
distracting approach of making the text's background colour bold.
.IP "\fBpterm.StampUtmp\fP"
This option should be set to either 0 or 1; the default is 1. When
set to 1, \fIpterm\fP will log the login in the various system log
files. This resource is equivalent to the \fI\-ut\fP command-line
option.
.IP "\fBpterm.LoginShell\fP"
This option should be set to either 0 or 1; the default is 1. When
set to 1, \fIpterm\fP will execute your shell as a login shell. This
resource is equivalent to the \fI\-ls\fP command-line option.
.SH BUGS
Most of the X resources have silly names. (Historical reasons from
PuTTY, mostly.)
