.TH putty 1
.UC
.SH NAME
putty \- GUI SSH, Telnet and Rlogin client for X
.SH SYNOPSIS
\fBputty\fP [ \fIoptions\fP ] [ \fIhost\fP ]
.SH DESCRIPTION
\fIputty\fP is a graphical SSH, Telnet and Rlogin client for X. It
is a direct port of the Windows SSH client of the same name.
.SH OPTIONS
The command-line options supported by \fIputty\fP are:
.IP "\fB\-\-display\fP \fIdisplay\-name\fP"
Specify the X display on which to open \fIputty\fP. (Note this
option has a double minus sign, even though none of the others do.
This is because this option is supplied automatically by GTK.
Sorry.)
.IP "\fB\-fn\fP \fIfont-name\fP"
Specify the font to use for normal text displayed in the terminal.
.IP "\fB\-fb\fP \fIfont-name\fP"
Specify the font to use for bold text displayed in the terminal. If
the \fIBoldAsColour\fP resource is set to 1 (the default), bold text
will be displayed in different colours instead of a different font,
so this option will be ignored. If \fIBoldAsColour\fP is set to 0
and you do not specify a bold font, \fIputty\fP will overprint the
normal font to make it look bolder.
.IP "\fB\-fw\fP \fIfont-name\fP"
Specify the font to use for double-width characters (typically
Chinese, Japanese and Korean text) displayed in the terminal.
.IP "\fB\-fwb\fP \fIfont-name\fP"
Specify the font to use for bold double-width characters (typically
Chinese, Japanese and Korean text) Like \fI-fb\fP, this will be
ignored unless the \fIBoldAsColour\fP resource is set to 0.
.IP "\fB\-geometry\fP \fIgeometry\fP"
Specify the size of the terminal, in rows and columns of text. See
\fIX(7)\fP for more information on the syntax of geometry
specifications.
.IP "\fB\-sl\fP \fIlines\fP"
Specify the number of lines of scrollback to save off the top of the
terminal.
.IP "\fB\-fg\fP \fIcolour\fP"
Specify the foreground colour to use for normal text.
.IP "\fB\-bg\fP \fIcolour\fP"
Specify the background colour to use for normal text.
.IP "\fB\-bfg\fP \fIcolour\fP"
Specify the foreground colour to use for bold text, if the
\fIBoldAsColour\fP resource is set to 1 (the default).
.IP "\fB\-bbg\fP \fIcolour\fP"
Specify the foreground colour to use for bold reverse-video text, if
the \fIBoldAsColour\fP resource is set to 1 (the default). (This
colour is best thought of as the bold version of the background
colour; so it only appears when text is displayed \fIin\fP the
background colour.)
.IP "\fB\-cfg\fP \fIcolour\fP"
Specify the foreground colour to use for text covered by the cursor.
.IP "\fB\-cbg\fP \fIcolour\fP"
Specify the background colour to use for text covered by the cursor.
In other words, this is the main colour of the cursor.
.IP "\fB\-title\fP \fItitle\fP"
Specify the initial title of the terminal window. (This can be
changed under control of the server.)
.IP "\fB\-sb\-\fP or \fB+sb\fP"
Tells \fIputty\fP not to display a scroll bar.
.IP "\fB\-sb\fP"
Tells \fIputty\fP to display a scroll bar: this is the opposite of
\fI\-sb\-\fP. This is the default option: you will probably only need
to specify it explicitly if you have changed the default using the
\fIScrollBar\fP resource.
.IP "\fB\-log\fP \fIfilename\fP"
This option makes \fIputty\fP log all the terminal output to a file
as well as displaying it in the terminal.
.IP "\fB\-cs\fP \fIcharset\fP"
This option specifies the character set in which \fIputty\fP should
assume the session is operating. This character set will be used to
interpret all the data received from the session, and all input you
type or paste into \fIputty\fP will be converted into this character
set before being sent to the session.

Any character set name which is valid in a MIME header (and
supported by \fIputty\fP) should be valid here (examples are
"ISO-8859-1", "windows-1252" or "UTF-8"). Also, any character
encoding which is valid in an X logical font description should be
valid ("ibm-cp437", for example).

\fIputty\fP's default behaviour is to use the same character
encoding as its primary font. If you supply a Unicode (iso10646-1)
font, it will default to the UTF-8 character set.

Character set names are case-insensitive.
.IP "\fB\-nethack\fP"
Tells \fIputty\fP to enable NetHack keypad mode, in which the
numeric keypad generates the NetHack "hjklyubn" direction keys. This
enables you to play NetHack with the numeric keypad without having
to use the NetHack "number_pad" option (which requires you to press
"n" before any repeat count). So you can move with the numeric
keypad, and enter repeat counts with the normal number keys.
.IP "\fB\-help\fP, \fB\-\-help\fP"
Display a message summarizing the available options.
.IP "\fB\-load\fP \fIsession\fP"
Load a saved session by name. This allows you to run a saved session
straight from the command line without having to go through the
configuration box first.
.IP "\fB\-ssh\fP, \fB\-telnet\fP, \fB\-rlogin\fP, \fB\-raw\fP"
Select the protocol \fIputty\fP will use to make the connection.
.IP "\fB\-l\fP \fIusername\fP"
Specify the username to use when logging in to the server.
.IP "\fB\-L\fP [\fIsrcaddr\fP:]\fIsrcport\fP:\fIdesthost\fP:\fIdestport\fP"
Set up a local port forwarding: listen on \fIsrcport\fP (or
\fIsrcaddr\fP:\fIsrcport\fP if specified), and forward any
connections over the SSH connection to the destination address
\fIdesthost\fP:\fIdestport\fP. Only works in SSH.
.IP "\fB\-R\fP [\fIsrcaddr\fP:]\fIsrcport\fP:\fIdesthost\fP:\fIdestport\fP"
Set up a remote port forwarding: ask the SSH server to listen on
\fIsrcport\fP (or \fIsrcaddr\fP:\fIsrcport\fP if specified),
and to forward any connections back over the SSH connection where
the client will pass them on to the destination address
\fIdesthost\fP:\fIdestport\fP. Only works in SSH.
.IP "\fB\-D\fP [\fIsrcaddr\fP:]\fIsrcport\fP"
Set up dynamic port forwarding. The client listens on \fIsrcport\fP
(or \fIsrcaddr\fP:\fIsrcport\fP if specified), and implements a
SOCKS server. So you can point SOCKS-aware applications at this port
and they will automatically use the SSH connection to tunnel all
their connections. Only works in SSH.
.IP "\fB\-P\fP \fIport\fP"
Specify the port to connect to the server on.
.IP "\fB\-A\fP, \fB\-a\fP"
Enable (\fB\-A\fP) or disable (\fB\-a\fP) SSH agent forwarding.
Currently this only works with OpenSSH and SSH1.
.IP "\fB\-X\fP, \fB\-x\fP"
Enable (\fB\-X\fP) or disable (\fB\-x\fP) X11 forwarding.
.IP "\fB\-T\fP, \fB\-t\fP"
Enable (\fB\-t\fP) or disable (\fB\-T\fP) the allocation of a
pseudo-terminal at the server end.
.IP "\fB\-C\fP, \fB\-t\fP"
Enable zlib-style compression on the connection.
.IP "\fB\-1\fP, \fB\-2\fP"
Select SSH protocol v1 or v2.
.IP "\fB\-i\fP \fIkeyfile\fP"
Specify a private key file to use for authentication. For SSH2 keys,
this key file must be in PuTTY's format, not OpenSSH's or anyone
else's.
.SH SAVED SESSIONS
Saved sessions are stored in a \fI.putty/sessions\fP subdirectory in
your home directory.
.SH MORE INFORMATION
For more information on PuTTY, it's probably best to go and look at
the manual on the web page:

\fBhttp://www.chiark.greenend.org.uk/~sgtatham/putty/\fP
.SH BUGS
This man page isn't terribly complete.

It's not very helpful to require a PuTTY-format SSH2 key file when
there isn't yet a Unix port of PuTTYgen.
