/* XPM */
static const char *const main_icon_0[] = {
/* columns rows colors chars-per-pixel */
"16 16 6 1",
"  c black",
". c blue",
"X c #808080",
"o c #C0C0C0",
"O c gray100",
"+ c None",
/* pixels */
"++++++++++++++++",
"++++++++++++++++",
"+++         ++++",
"++ OOOOOOOoX +++",
"++ O......oX +++",
"++ O......oX +++",
"++ O......oX +++",
"++ O......oX +++",
"++ O......oX +++",
"++ ooooooooX  ++",
"+ XXXXXXXXXXOX +",
" OOOOOOOOOOOoX +",
" OoooooXXXXoXX +",
"+             ++",
"++++++++++++++++",
"++++++++++++++++"
};

/* XPM */
static const char *const main_icon_1[] = {
/* columns rows colors chars-per-pixel */
"32 32 7 1",
"  c black",
". c navy",
"X c blue",
"o c #808080",
"O c #C0C0C0",
"+ c gray100",
"@ c None",
/* pixels */
"@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@",
"@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@",
"@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@",
"@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@",
"@@@@@@@@                @@@@@@@@",
"@@@@@@@ OOOOOOOOOOOOOOOo @@@@@@@",
"@@@@@@ OOOOOOOOOOOOOOOoo @@@@@@@",
"@@@@@ ++++++++++++++Oooo @@@@@@@",
"@@@@@ +.............Oooo @@@@@@@",
"@@@@@ +.XXXXXXXXXXXXOooo @@@@@@@",
"@@@@@ +.XXXXXXXXXXXXOooo @@@@@@@",
"@@@@@ +.XXXXXXXXXXXXOooo @@@@@@@",
"@@@@@ +.XXXXXXXXXXXXOooo @@@@@@@",
"@@@@@ +.XXXXXXXXXXXXOooo @@@@@@@",
"@@@@@ +.XXXXXXXXXXXXOooo @@@@@@@",
"@@@@@ +.XXXXXXXXXXXXOooo @@@@@@@",
"@@@@@ +.XXXXXXXXXXXXOooo @@@@@@@",
"@@@@@ ++++++++++++++Oooo @@@@@@@",
"@@@@@ +OOOOOOOOOOOOOooo      @@@",
"@@@@  Oooooooooooooooo OOOO+o @@",
"@@@ O                 OOOO+oo @@",
"@@ OOOOOOOOOOOOOOOOOOOOOO+ooo @@",
"@ +++++++++++++++++++++++Oooo @@",
"@ +OOOOOOOOOOOOOOOOOOOOOOoooo @@",
"@ +OOOOOOOOOOOOo      oOOooo @@@",
"@ Ooooooooooooooooooooooooo @@@@",
"@@                         @@@@@",
"@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@",
"@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@",
"@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@",
"@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@",
"@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@"
};

/* XPM */
static const char *const main_icon_2[] = {
/* columns rows colors chars-per-pixel */
"48 48 7 1",
"  c black",
". c navy",
"X c blue",
"o c #808080",
"O c #C0C0C0",
"+ c gray100",
"@ c None",
/* pixels */
"@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@",
"@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@",
"@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@",
"@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@",
"@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@",
"@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@",
"@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@",
"@@@@@@@@@@@@@                        @@@@@@@@@@@",
"@@@@@@@@@@@@ OOOOOOOOOOOOOOOOOOOOOOOo @@@@@@@@@@",
"@@@@@@@@@@@ OOOOOOOOOOOOOOOOOOOOOOOoo @@@@@@@@@@",
"@@@@@@@@@@ OOOOOOOOOOOOOOOOOOOOOOOooo @@@@@@@@@@",
"@@@@@@@@@ ++++++++++++++++++++++Ooooo @@@@@@@@@@",
"@@@@@@@@@ +ooooooooooooooooooooOooooo @@@@@@@@@@",
"@@@@@@@@@ +o...................+ooooo @@@@@@@@@@",
"@@@@@@@@@ +o.XXXXXXXXXXXXXXXXXX+ooooo @@@@@@@@@@",
"@@@@@@@@@ +o.XXXXXXXXXXXXXXXXXX+ooooo @@@@@@@@@@",
"@@@@@@@@@ +o.XXXXXXXXXXXXXXXXXX+ooooo @@@@@@@@@@",
"@@@@@@@@@ +o.XXXXXXXXXXXXXXXXXX+ooooo @@@@@@@@@@",
"@@@@@@@@@ +o.XXXXXXXXXXXXXXXXXX+ooooo @@@@@@@@@@",
"@@@@@@@@@ +o.XXXXXXXXXXXXXXXXXX+ooooo @@@@@@@@@@",
"@@@@@@@@@ +o.XXXXXXXXXXXXXXXXXX+ooooo @@@@@@@@@@",
"@@@@@@@@@ +o.XXXXXXXXXXXXXXXXXX+ooooo @@@@@@@@@@",
"@@@@@@@@@ +o.XXXXXXXXXXXXXXXXXX+ooooo @@@@@@@@@@",
"@@@@@@@@@ +o.XXXXXXXXXXXXXXXXXX+ooooo @@@@@@@@@@",
"@@@@@@@@@ +o.XXXXXXXXXXXXXXXXXX+ooooo @@@@@@@@@@",
"@@@@@@@@@ +o.XXXXXXXXXXXXXXXXXX+ooooo @@@@@@@@@@",
"@@@@@@@@@ +o.XXXXXXXXXXXXXXXXXX+ooooo @@@@@@@@@@",
"@@@@@@@@@ +O++++++++++++++++++++ooooo @@@@@@@@@@",
"@@@@@@@@  +OOOOOOOOOOOOOOOOOOOOOoooo        @@@@",
"@@@@@@@ O +OOOOOOOOOOOOOOOOOOOOOooo OOOOO++o @@@",
"@@@@@@ OO Oooooooooooooooooooooooo OOOOO++oo @@@",
"@@@@@ OOO                         OOOOO++ooo @@@",
"@@@@ OOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO++oooo @@@",
"@@@ +++++++++++++++++++++++++++++++++++Ooooo @@@",
"@@@ ++++++++++++++++++++++++++++++++++Oooooo @@@",
"@@@ ++OOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOoooooo @@@",
"@@@ ++OOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOooooo @@@@",
"@@@ ++OOOOOOOOOOOOOOOOOO          oOOOoooo @@@@@",
"@@@ OOooooooooooooooooooooooooooooooooooo @@@@@@",
"@@@@                                     @@@@@@@",
"@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@",
"@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@",
"@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@",
"@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@",
"@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@",
"@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@",
"@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@",
"@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@"
};

const char *const *const main_icon[] = {
    main_icon_0,
    main_icon_1,
    main_icon_2,
};
const int n_main_icon = 3;
