/* XPM */
static const char *const cfg_icon_0[] = {
/* columns rows colors chars-per-pixel */
"16 16 9 1",
"  c black",
". c navy",
"X c blue",
"o c #808000",
"O c yellow",
"+ c #808080",
"@ c #C0C0C0",
"# c gray100",
"$ c None",
/* pixels */
"$$$  $       $$$",
"$$ OO #####@+ $$",
"$ $ oO+XXX.++ $$",
" o $ oO.X.O++ $$",
" oO  OO .O.@+  $",
"$ oOOOOoO+@@+++ ",
"$$ oooOOoO ++@+ ",
"$$  oooOO +++++ ",
"$ ##+OooOO     $",
"$ #.O..+oOO $$$$",
"$ +O.XX@ oOO $$$",
"$ +.XXX@+ oOO $$",
"$ @@@@@@++ oOO $",
" ++++++++@+ oOO ",
" #@@@@+++++  oO ",
"$          $$  $"
};

/* XPM */
static const char *const cfg_icon_1[] = {
/* columns rows colors chars-per-pixel */
"32 32 9 1",
"  c black",
". c navy",
"X c blue",
"o c #808000",
"O c yellow",
"+ c #808080",
"@ c #C0C0C0",
"# c gray100",
"$ c None",
/* pixels */
"$$$$$$$$$$$$$$$$            $$$$",
"$$$$$$  $$$$$$$ @@@@@@@@@@@+ $$$",
"$$$$$ OO  $$$$ ##########@++ $$$",
"$$$$$ ooOO $$$ #.........@++ $$$",
"$$$$$$ ooOO $$ #.XXXXXXXX@++ $$$",
"$$  $$$ oOO $$ #.XXXX  XX@++ $$$",
"$ oO $$ oOOO $ #.XXX O XX@++ $$$",
"$ oOO  oOOOO $ #.X  O XXX@++ $$$",
"$$ oOOOOOOO $$ #. OO XXXX@++ $$$",
"$$ ooOOOOOOO $ # OO XXXXX@++ $$$",
"$$$ ooooooOOO   OO ######@++   $",
"$$$$  oo ooOOO OO +++++++++ @#+ ",
"$$$$$$  $ ooOOO            @#++ ",
"$$$$$$$$$$ ooOOO OOO #######@++ ",
"$$$$$$$$$ O ooOOO   @@@@@@@@+++ ",
"$$$$$        ooOOO @@+    +@++ $",
"$$$$ @@@@@@@  ooOOO           $$",
"$$$ ####### OO ooOOO $$$$$$$$$$$",
"$$$ #..... OO @ ooOOO $$$$$$$$$$",
"$$$ #.XXX OO X@+ ooOOO $$$$$$$$$",
"$$$ #.XX O  XX@++ ooOOO $$$$$$$$",
"$$$ #.X O XXXX@++  ooOOO $$$$$$$",
"$$$ #.X  XXXXX@++ $ ooOOO $$$$$$",
"$$$ #.XXXXXXXX@++ $$ ooOOO $$$$$",
"$$$ #.XXXXXXXX@++ $$$ ooOOO $$$$",
"$$$ ##########@++   $$ ooOOO $$$",
"$$  @+++++++++++ @#+ $$ ooOOO $$",
"$ @             @#++ $$$ ooO $$$",
" ################@++ $$$$ o $$$$",
" #@@@@@@@@@@@@@@@+++ $$$$$ $$$$$",
" #@@@@@@@@+    +@++ $$$$$$$$$$$$",
"$                  $$$$$$$$$$$$$"
};

/* XPM */
static const char *const cfg_icon_2[] = {
/* columns rows colors chars-per-pixel */
"48 48 9 1",
"  c black",
". c navy",
"X c blue",
"o c #808000",
"O c yellow",
"+ c #808080",
"@ c #C0C0C0",
"# c gray100",
"$ c None",
/* pixels */
"$$$$$$$$$$$$$$$$$$$$$$$$                  $$$$$$",
"$$$$$$$$$$$$$$$$$$$$$$$ @@@@@@@@@@@@@@@@@+ $$$$$",
"$$$$$$$$$  $$$$$$$$$$$ @@@@@@@@@@@@@@@@@++ $$$$$",
"$$$$$$$$ OO   $$$$$$$ ################@+++ $$$$$",
"$$$$$$$$ oOOOO $$$$$$ #++++++++++++++@++++ $$$$$",
"$$$$$$$$$ ooOOO $$$$$ #+.............#++++ $$$$$",
"$$$$$$$$$$ ooOOO $$$$ #+.XXXXXXXXXXXX#++++ $$$$$",
"$$$$$$$$$$$ oOOO $$$$ #+.XXXXXXXXXXXX#++++ $$$$$",
"$$$  $$$$$$ oOOO $$$$ #+.XXXXXXX  XXX#++++ $$$$$",
"$$ oO $$$$$ oOOOO $$$ #+.XXXXXX O XXX#++++ $$$$$",
"$$ ooO $$$$ oOOOO $$$ #+.XXXXX O XXXX#++++ $$$$$",
"$$$ oOO    OOOOO $$$$ #+.XXX  O XXXXX#++++ $$$$$",
"$$$ ooOOOOOOOOOOO $$$ #+.XX OO XXXXXX#++++ $$$$$",
"$$$ ooOOOOOOOOOOOO $$ #+.X OO XXXXXXX#++++ $$$$$",
"$$$$ oooOOOOoOOOOOO $ #@  OO #########++++     $",
"$$$$$ oooooooOOOOOOO  # OOO @@@@@@@@@@+++ @@##+ ",
"$$$$$$   oo ooOOOOOOO  OO  +++++++++++++ @@##++ ",
"$$$$$$$$$  $ ooOOOOOOO O                @@##+++ ",
"$$$$$$$$$$$$$ ooOOOOOOO      ##############@+++ ",
"$$$$$$$$$$$$$$ ooOOOOOOO OOOO ############@++++ ",
"$$$$$$$$$$$$$$$ ooOOOOOOO O  @@@@@@@@@@@@@+++++ ",
"$$$$$$$$$$$$$$$  ooOOOOOOO @@@@@+       @@++++ $",
"$$$$$$$$$$$$$$ OO ooOOOOOOO +++++++++++++++++ $$",
"$$$$$$$$$$$$$$$    ooOOOOOOO                 $$$",
"$$$$$$$             ooOOOOOOO $$$$$$$$$$$$$$$$$$",
"$$$$$$ @@@@@@@@@@  O ooOOOOOOO $$$$$$$$$$$$$$$$$",
"$$$$$ @@@@@@@@@@ OOO  ooOOOOOOO $$$$$$$$$$$$$$$$",
"$$$$ ########## OO  #@ ooOOOOOOO $$$$$$$$$$$$$$$",
"$$$$ #++++++++ OO ++@++ ooOOOOOOO $$$$$$$$$$$$$$",
"$$$$ #+...... OO ...#+++ ooOOOOOOO $$$$$$$$$$$$$",
"$$$$ #+.XXXX O  XXXX#++++ ooOOOOOOO $$$$$$$$$$$$",
"$$$$ #+.XXX O XXXXXX#++++  ooOOOOOOO $$$$$$$$$$$",
"$$$$ #+.XX O XXXXXXX#++++ $ ooOOOOOOO $$$$$$$$$$",
"$$$$ #+.XX  XXXXXXXX#++++ $$ ooOOOOOOO $$$$$$$$$",
"$$$$ #+.XXXXXXXXXXXX#++++ $$$ ooOOOOOOO $$$$$$$$",
"$$$$ #+.XXXXXXXXXXXX#++++ $$$$ ooOOOOOOO $$$$$$$",
"$$$$ #+.XXXXXXXXXXXX#++++ $$$$$ ooOOOOOOO $$$$$$",
"$$$$ #+.XXXXXXXXXXXX#++++ $$$$$$ ooOOOOOOO $$$$$",
"$$$$ #@##############++++     $$$ ooOOOOOOO $$$$",
"$$$  #@@@@@@@@@@@@@@@+++ @@##+ $$$ ooOOOOOOO $$$",
"$$ @ @+++++++++++++++++ @@##++ $$$$ ooOOOOO $$$$",
"$ @@                   @@##+++ $$$$$ ooOOO $$$$$",
" #########################@+++ $$$$$$ ooO $$$$$$",
" ########################@++++ $$$$$$$ o $$$$$$$",
" ##@@@@@@@@@@@@@@@@@@@@@@+++++ $$$$$$$$ $$$$$$$$",
" ##@@@@@@@@@@@@+       @@++++ $$$$$$$$$$$$$$$$$$",
" @@+++++++++++++++++++++++++ $$$$$$$$$$$$$$$$$$$",
"$                           $$$$$$$$$$$$$$$$$$$$"
};

const char *const *const cfg_icon[] = {
    cfg_icon_0,
    cfg_icon_1,
    cfg_icon_2,
};
const int n_cfg_icon = 3;
